### ISSUE TITLE
Inhalt der Referenztabellen nicht verknüpft

### ISSUE THREAD

**Issue by schorsch2** [hoettges/QKan#15]
Ich versuche, einen Profiltyp oder den Planungsstatus einer Haltung zuzuweisen. Die Netzdaten habe ich über die ISYBAU- XML- Schnittstelle importiert. Allerdings sind keine Daten der Referenztabellen in der Eingabemaske auswählbar. Die Darstellung in Klammern scheint ein Hinweis darauf, dass die Verknüpfung irgendwie schief gegangen ist.

![grafik](https://github.com/hoettges/QKan/assets/13661057/74d0ab40-a00f-4993-b5e5-d5c796d38564)

**Comment by noblase** [comment]
Entschuldigung für die späte Beantwortung der Frage. Die Darstellung in Klammern deutet immer daraufhin, dass der jeweilige Wert nicht in der Referenztabelle vorhanden ist. Wenn der Wert in der jeweiligen Referenztabelle ergänzt wurde verschwinden die Klammern.
