### ISSUE TITLE
SWMM- Export [MAP] mit unzulässigen Zeichen

### ISSUE THREAD

**Issue by schorsch2** [hoettges/QKan#17]
Der Export nach SWMM mit der Option "Einzugsgebiete" eingeschalten führt zu einer Fehlermeldung in SWMM. Ursache ist offenbar, dass im Abschnitt [MAP] unzulässige Zeichen auftauchen:
`[MAP]
DIMENSIONS< 5473640.52176199574023485 5655056.69378227647393942 5474198.72497421037405729 5655306.2852822607383132> 
`
Das Beispiel in der SWMM- Dokumentation sieht so aus:
`[MAP] 
 DIMENSIONS 0.00 0.00 10000.00 10000.00
 UNITS None`
Lösche ich die Zeichen "<" und ">" manuell, wird das exportierte File in SWMM akzeptiert.

**Comment by noblase** [comment]
Entschuldigung für die späte Rückmeldung. Den Hinweis haben wir eingearbeitet. Der Fehler sollte bei der nächsten Version nicht mehr auftreten.
