### ISSUE TITLE
SWMM-Export mit ungültigen Zeichen

### ISSUE THREAD

**Issue by schorsch2** [hoettges/QKan#22]
Der SWMM-Export läuft durch, erzeugt jedoch ungültige Zeichen, die beim Import in SWMM zu fehlern führen. 
![grafik](https://github.com/user-attachments/assets/3505b964-a5e3-4d10-9c23-319e7d843f36) 
Entfernt man die Klammern <> um die Koordinaten, läuft der Import durch.

**Comment by noblase** [comment]
Hallo, den Fehler haben wir behoben. In der nächsten Version sollte er nicht mehr auftreten.
