### ISSUE TITLE
import swmm rewrite

### ISSUE THREAD

**Issue by Jannik-Schilling** [hoettges/QKan#9]
currently swmm inp files are imported using hard coded postitions in the lines of the text file, e.g. https://github.com/hoettges/QKan/blob/qkan3/qkan/swmmporter/_importSWMM.py (208 - 211)
```
for line in data:
            name = line[**0:17**].strip()  # schnam
            elevation = line[17:28].strip()  # sohlhoehe
            outtype = line[28:39].strip()  # Auslasstyp
```
However SWMM uses another concept: "separators" (whitespace, tab) separate "tokens" (any values) in swmm lines. And the values (e.g. names) can be longer than 17 characters!

**Comment by Jannik-Schilling** [comment]
see https://github.com/Jannik-Schilling/generate_swmm_inp/blob/main/generate_swmm_import_inp_file.py line 286

**Comment by Jannik-Schilling** [comment]
[487aa6f](https://github.com/Jannik-Schilling/QKan/commit/487aa6f18a10f78c5668c156ae22cb4ce35e05ba)

**Comment by noblase** [comment]
Hello @Jannik-Schilling ,
we are very thankfull for your comments and also for fixing this problem. We will soon accept your changes so that they are in the new releases.
Also we fixed the SWMM Export this change will also be in one of the next versions.
